version: '3'

networks:
  proxy:
    driver: bridge

services:
  nginx: 
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80 
    networks:
      - proxy

  web-blue:
    image:  fabricioveronez/web-color:blue
    networks:
      - proxy

  web-green:
    image:  fabricioveronez/web-color:green
    networks:
      - proxy